server :
  port : 8080
  session:
    timeout : 600

spring:
  boot:
    admin:
      client:
        auto-registration: true
        url: http://127.0.0.1:8090
        instance:
          name: WebSiteOne_Monitor
#          service-base-url: https://usr.secum.kr/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"