server :
  port : 18080
  session:
    timeout : 600

spring:
  boot:
    admin:
      client:
        auto-registration: true
        url: http://localhost:19090
        instance:
          name: Test_Monitor
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
         include: "*"
#        include: health, info, metrics, loggers, mappings, prometheus, startup, shutdown, sessions, process